GRANT SELECT ON PHANCONG TO NhanVienCoBan;
GRANT SELECT ON SINHVIEN TO NhanVienCoBan;
GRANT SELECT ON DONVI TO NhanVienCoBan;
GRANT SELECT ON HOCPHAN TO NhanVienCoBan;

GRANT SELECT ON SINHVIEN TO NVCB_100;
GRANT SELECT ON DONVI TO NVCB_100;
GRANT SELECT ON HOCPHAN TO NVCB_100;

GRANT UPDATE ON HOCPHAN TO GVU_88;
GRANT INSERT ON HOCPHAN TO GVU_88;
GRANT DELETE ON HOCPHAN TO GVU_88;

GRANT UPDATE ON HOCPHAN TO GVU_89 WITH GRANT OPTION;
GRANT INSERT ON HOCPHAN TO GVU_89 WITH GRANT OPTION;
GRANT DELETE ON HOCPHAN TO GVU_89 WITH GRANT OPTION;