--B1: TẠO PDB BẰNG DATABASE CONFIGURATION ASSISTANT 
-- CHỌN TẠO PDB --> CHỌN CDB@ROOT MUỐN TẠO PDB BÊN TRONG --> CHỌN THIẾT LẬP NHƯ HÌNH --> ĐẶT TÊN CHO PDB: PDBQLDLNB --> CHỌN NEXT --> CHỌN FISNISH
-- CHẠY VỚI QUYỀN SYS (CONNECT sys/21127659)
--B2: THIẾT LẬP TRƯỚC KHI TẠO CÁC CHÍNH SÁCH OLS
---> KIỂM TRA OLS ĐÃ ĐƯỢC BẬT CHƯA (CONNECT = SYS USER) 
SELECT VALUE FROM v$option WHERE parameter = 'Oracle Label Security';
SELECT status FROM dba_ols_status WHERE name = 'OLS_CONFIGURE_STATUS'; 
---> BẬT OLS NẾU CHƯA BẬT/ CHƯA ĐĂNG KÝ THÌ ĐĂNG KÝ OLS VÀ BẬT OLS 
EXEC LBACSYS.CONFIGURE_OLS;
EXEC LBACSYS.OLS_ENFORCEMENT.ENABLE_OLS;
/
---> KHỞI ĐỘNG LẠI
SHUTDOWN IMMEDIATE;
STARTUP;
/
---> KIỂM TRA PDB CÓ CHƯA (VÌ KO THỂ TẠO OLS TREN CDB)
select * from v$services; 
---> UNLOCK LBACSYS (OLS ADMIN)
ALTER USER lbacsys IDENTIFIED BY lbacsys ACCOUNT UNLOCK;
---> NẾU CÓ RỒI THÌ MỞ PDB
ALTER PLUGGABLE DATABASE PDBQLDLNB OPEN READ WRITE;
-- SELECT NAME, OPEN_MODE FROM V$PDBS WHERE NAME = 'PDBQLBH';
---> CHUYỂN QUA PDB 
ALTER SESSION SET CONTAINER = PDBQLDLNB;
SHOW CON_NAME;
/
--TẠO USER = U_ADMIN
---> TẠO U_ADMIN OLS & CẤP QUYỀN CHO U_ADMIN
--ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;
--DROP USER U_ADMIN CASCADE;
--/
--CREATE USER U_ADMIN IDENTIFIED BY 123 CONTAINER = CURRENT;
GRANT CONNECT,RESOURCE TO U_ADMIN; --CẤP QUYỀN CONNECT VÀ RESOURCE
GRANT UNLIMITED TABLESPACE TO U_ADMIN; --CẤP QUOTA CHO ADMIN_OLS
GRANT SELECT ANY DICTIONARY TO U_ADMIN; --CẤP QUYỀN ĐỌC DICTIONARY
---> CẤP QUYỀN EXECUTE CHO U_ADMIN
GRANT EXECUTE ON LBACSYS.SA_COMPONENTS TO U_ADMIN WITH GRANT OPTION;
GRANT EXECUTE ON LBACSYS.sa_user_admin TO U_ADMIN WITH GRANT OPTION;
GRANT EXECUTE ON LBACSYS.sa_label_admin TO U_ADMIN WITH GRANT OPTION;
GRANT EXECUTE ON sa_policy_admin TO U_ADMIN WITH GRANT OPTION;
GRANT EXECUTE ON char_to_label TO U_ADMIN WITH GRANT OPTION;
---> ADD ADMIN_OLS VÀO LBAC_DBA
SELECT * FROM DBA_SYS_PRIVS WHERE GRANTEE = 'U_ADMIN';
GRANT LBAC_DBA TO U_ADMIN;
GRANT EXECUTE ON sa_sysdba TO U_ADMIN WITH GRANT OPTION;
GRANT EXECUTE ON TO_LBAC_DATA_LABEL TO U_ADMIN; -- CẤP QUYỀN THỰC THI
--B3: BẮT ĐẦU TẠO CHÍNH SÁCH OLS (CONNECT VÀO TÀI KHOẢN U_ADMIN)
-- TẠO CHÍNH SÁCH OLS (KHỞI ĐỘNG LẠI SQLDEV ĐỂ CẬP NHẬT OLS ENABLE)
BEGIN
SA_SYSDBA.CREATE_POLICY(
    policy_name => 'THONGBAO_OLS',
    column_name => 'row_label'
);
END;
/
--ENABLE POLICY VỪA TẠO -> KHOI DONG LẠI SQLDEV
EXEC SA_SYSDBA.ENABLE_POLICY ('THONGBAO_OLS');
/
SHUTDOWN IMMEDIATE;
STARTUP;
/
--TẠO COMPONENT CỦA LABEL
--->TẠO LEVEL
BEGIN
SA_COMPONENTS.CREATE_LEVEL(
    POLICY_NAME => 'THONGBAO_OLS',
    LONG_NAME => 'Truong khoa',
    SHORT_NAME => 'TK',
    LEVEL_NUM => 600);

SA_COMPONENTS.CREATE_LEVEL(
    POLICY_NAME => 'THONGBAO_OLS',
    LONG_NAME => 'Truong don vi',
    SHORT_NAME => 'TDV',
    LEVEL_NUM => 500);

SA_COMPONENTS.CREATE_LEVEL(
    POLICY_NAME => 'THONGBAO_OLS',
    LONG_NAME => 'Giang vien',
    SHORT_NAME => 'GV',
    LEVEL_NUM => 400);
    
SA_COMPONENTS.CREATE_LEVEL(
    POLICY_NAME => 'THONGBAO_OLS',
    LONG_NAME => 'Giao vu',
    SHORT_NAME => 'GVU',
    LEVEL_NUM => 300);

SA_COMPONENTS.CREATE_LEVEL(
    POLICY_NAME => 'THONGBAO_OLS',
    LONG_NAME => 'Nhan vien',
    SHORT_NAME => 'NV',
    LEVEL_NUM => 200);

SA_COMPONENTS.CREATE_LEVEL(
    POLICY_NAME => 'THONGBAO_OLS',
    LONG_NAME => 'Sinh vien',
    SHORT_NAME => 'SV',
    LEVEL_NUM => 100);
END;
--->TẠO COMPARTMENT: HTTT, CNPM, KHMT, CNTT, TGMT, MMT
EXECUTE SA_COMPONENTS.CREATE_COMPARTMENT('THONGBAO_OLS',1000,'HTTT','He thong thong tin');
EXECUTE SA_COMPONENTS.CREATE_COMPARTMENT('THONGBAO_OLS',1200,'CNPM','Cong nghe phan mem');
EXECUTE SA_COMPONENTS.CREATE_COMPARTMENT('THONGBAO_OLS',1400,'KHMT','Khoa hoc may tinh');
EXECUTE SA_COMPONENTS.CREATE_COMPARTMENT('THONGBAO_OLS',1600,'CNTT','Cong nghe thong tin');
EXECUTE SA_COMPONENTS.CREATE_COMPARTMENT('THONGBAO_OLS',1800,'TGMT','Thi giac may tinh');
EXECUTE SA_COMPONENTS.CREATE_COMPARTMENT('THONGBAO_OLS',2000,'MMT','Mang may tinh');
--->TẠO GROUP
EXECUTE SA_COMPONENTS.CREATE_GROUP('THONGBAO_OLS',20,'CS1','Co so 1');
EXECUTE SA_COMPONENTS.CREATE_GROUP('THONGBAO_OLS',40,'CS2','Co so 2');

-- ===== CHAY DUOI QUYEN SYS =====
--B4: CONNECT SYS KIỂM TRA COMPONENT TẠO ĐÚNG CHƯA
SELECT * FROM DBA_SA_LEVELS;
SELECT * FROM DBA_SA_COMPARTMENTS;
SELECT * FROM DBA_SA_GROUPS;
SELECT * FROM DBA_SA_GROUP_HIERARCHY;
-- ===== CHAY DUOI QUYEN U_ADMIN =====
-- XOÁ BẢNG
DROP TABLE THONGBAO PURGE;
--B5: TẠO BẢNG DỮ LIỆU TEST
CREATE TABLE THONGBAO(
    NOIDUNG VARCHAR2(255),
    NGAYGIO DATE,
    DIADIEM VARCHAR2(255),
    CAPBACTHAMGIA NUMBER, -- 1.Trưởng khoa, 2.Trưởng don vi, 3.Giảng viên, 4.Giáo vụ, 5.Nhân viên, 6.Sinh viên
    LINHVUC NUMBER, -- 1.HTTT, 2.CNPM, 3.KHMT, 4.CNTT, 5.TGMT, 6.MMT
    COSO NUMBER -- 1.Cơ sở 1, 2.Cơ sở 2
);
-- Them du lieu vao bang THONGBAO
-- Chèn thông báo minh họa
INSERT INTO THONGBAO (NOIDUNG, NGAYGIO, DIADIEM, CAPBACTHAMGIA, LINHVUC, COSO)
VALUES ('Thong bao cuoc hop quan trong ve ke hoach giang day lop He thong thong tin', TO_DATE('2023/12/16', 'yyyy/mm/dd '), 'Quan 5', 1, 1, 1);
INSERT INTO THONGBAO (NOIDUNG, NGAYGIO, DIADIEM, CAPBACTHAMGIA, LINHVUC, COSO)
VALUES ('Thong bao cuoc hop quan trong ve ke hoach giang day lop Cong nghe phan mem', TO_DATE('2023/10/05', 'yyyy/mm/dd '), 'Thu Duc', 1, 2, 0);
INSERT INTO THONGBAO (NOIDUNG, NGAYGIO, DIADIEM, CAPBACTHAMGIA, LINHVUC, COSO)
VALUES ('Thong bao cuoc hop quan trong ve ke hoach giang day lop Khoa hoc may tinh', TO_DATE('2023/12/16', 'yyyy/mm/dd '), 'Quan 5', 1, 3, 1);
INSERT INTO THONGBAO (NOIDUNG, NGAYGIO, DIADIEM, CAPBACTHAMGIA, LINHVUC, COSO)
VALUES ('Thong bao cuoc hop quan trong ve ke hoach giang day lop Cong nghe thong tin', TO_DATE('2023/02/23', 'yyyy/mm/dd '), 'Thu Duc', 1, 4, 0);
INSERT INTO THONGBAO (NOIDUNG, NGAYGIO, DIADIEM, CAPBACTHAMGIA, LINHVUC, COSO)
VALUES ('Thong bao ve lich nghi le tet', TO_DATE('2024/02/05', 'yyyy/mm/dd '), 'Thu Duc', 6, 0, 2);
INSERT INTO THONGBAO (NOIDUNG, NGAYGIO, DIADIEM, CAPBACTHAMGIA, LINHVUC, COSO)
VALUES ('Thong bao ve viec nop bai tap lon', TO_DATE('2023/10/06', 'yyyy/mm/dd '), 'Quan 5', 3, 0, 1);
-- Chèn thông báo cho giáo vụ
INSERT INTO THONGBAO (NOIDUNG, NGAYGIO, DIADIEM, CAPBACTHAMGIA, LINHVUC, COSO)
VALUES ('Thong bao ve lich hoc moi cua hoc ky sau', TO_DATE('2023/12/16', 'yyyy/mm/dd '), 'Quan 5', 6, 0, 1);
INSERT INTO THONGBAO (NOIDUNG, NGAYGIO, DIADIEM, CAPBACTHAMGIA, LINHVUC, COSO)
VALUES ('Thong bao ve ke hoach to chuc thi cuoi ky cho lop Thi giac may tinh', TO_DATE('2024/02/21', 'yyyy/mm/dd '), 'Quan 5', 6, 5, 1);
INSERT INTO THONGBAO (NOIDUNG, NGAYGIO, DIADIEM, CAPBACTHAMGIA, LINHVUC, COSO)
VALUES ('Thong bao ve viec phan cong do an cuoi khoa', TO_DATE('2024/01/31', 'yyyy/mm/dd '), 'Thu Duc', 6, 0, 2);
INSERT INTO THONGBAO (NOIDUNG, NGAYGIO, DIADIEM, CAPBACTHAMGIA, LINHVUC, COSO)
VALUES ('Thong bao ve cuoc hop ke hoach truoc Tet', TO_DATE('2023/12/20', 'yyyy/mm/dd '), 'Quan 5', 4, 0, 0);
INSERT INTO THONGBAO (NOIDUNG, NGAYGIO, DIADIEM, CAPBACTHAMGIA, LINHVUC, COSO)
VALUES ('Thong bao ve ngay nha giao Viet Nam', TO_DATE('2024/11/10', 'yyyy/mm/dd '), 'Quan 5', 4, 5, 0);
INSERT INTO THONGBAO (NOIDUNG, NGAYGIO, DIADIEM, CAPBACTHAMGIA, LINHVUC, COSO)
VALUES ('Thong bao ve ke hoach to chuc tiec cuoi nam', TO_DATE('2024/01/15', 'yyyy/mm/dd '), 'Quan 5', 4, 0, 12);
-- Chèn thông báo cho trưởng don vi
INSERT INTO THONGBAO (NOIDUNG, NGAYGIO, DIADIEM, CAPBACTHAMGIA, LINHVUC, COSO)
VALUES ('Thong bao ve lich hoc moi cua phong A', TO_DATE('2024/03/26', 'yyyy/mm/dd '), 'Thu Duc', 2, 0, 2);
INSERT INTO THONGBAO (NOIDUNG, NGAYGIO, DIADIEM, CAPBACTHAMGIA, LINHVUC, COSO)
VALUES ('Thong bao ve ke hoach to chuc hoi thao', TO_DATE('2024/05/11', 'yyyy/mm/dd '), 'Thu Duc', 2, 0, 2);
INSERT INTO THONGBAO (NOIDUNG, NGAYGIO, DIADIEM, CAPBACTHAMGIA, LINHVUC, COSO)
VALUES ('Thong bao ve viec to chuc sinh nhat cua don vi', TO_DATE('2024/01/31', 'yyyy/mm/dd '), 'Quan 5', 2, 0, 1);
-- Chèn thông báo cho sinh viên HTTT
INSERT INTO THONGBAO (NOIDUNG, NGAYGIO, DIADIEM, CAPBACTHAMGIA, LINHVUC, COSO)
VALUES ('Thong bao ve lich hoc moi cua hoc ky sau cua lop He thong thong tin', TO_DATE('2023/12/16', 'yyyy/mm/dd'), 'Quan 5', 6, 1, 1);
INSERT INTO THONGBAO (NOIDUNG, NGAYGIO, DIADIEM, CAPBACTHAMGIA, LINHVUC, COSO)
VALUES ('Thong bao ve ke hoach to chuc thi cuoi ky cho lop He thong thong tin', TO_DATE('2024/02/21', 'yyyy/mm/dd'), 'Quan 5', 6, 1, 1);
INSERT INTO THONGBAO (NOIDUNG, NGAYGIO, DIADIEM, CAPBACTHAMGIA, LINHVUC, COSO)
VALUES ('Thong bao bao ve luan van tot nghiep', TO_DATE('2024/01/31', 'yyyy/mm/dd'), 'Thu Duc', 6, 0, 2);
/
SELECT * FROM THONGBAO;
--B7: CẬP NHẬT NHÃN TRONG BẢNG
SA_POLICY_ADMIN.APPLY_TABLE_POLICY(
    POLICY_NAME => 'THONGBAO_OLS',
    SCHEMA_NAME => 'U_ADMIN',
    TABLE_NAME => 'THONGBAO',
    TABLE_OPTIONS => 'NO_CONTROL');
END;
/
--B6: TẠO NHÃN
----TẠO THỦ CÔNG BẰNG LỆNH
EXECUTE SA_LABEL_ADMIN.CREATE_LABEL('THONGBAO_OLS',2330,'TK:HTTT,CNPM,KHMT,CNTT,TGMT,MMT:CS1,CS2'); --a. Trưởng khoa có thể đọc được toàn bộ thông báo.
EXECUTE SA_LABEL_ADMIN.CREATE_LABEL('THONGBAO_OLS',2450,'TDV:HTTT,CNPM,KHMT,CNTT,TGMT,MMT:CS1,CS2'); --b. Trưởng bộ môn phụ trách Cơ sở 2 có thể đọc được toàn bộ thông báo dành cho trưởng bộ môn không phân biệt vị trí địa lý.
EXECUTE SA_LABEL_ADMIN.CREATE_LABEL('THONGBAO_OLS',2560,'GVU:HTTT,CNPM,KHMT,CNTT,TGMT,MMT:CS1,CS2'); --c.  Giáo vụ có thể đọc toàn bộ thông báo dành cho giáo vụ 

EXECUTE SA_LABEL_ADMIN.CREATE_LABEL('THONGBAO_OLS',2230,'TK:HTTT,CNPM,KHMT,CNTT,TGMT,MMT:CS1');
EXECUTE SA_LABEL_ADMIN.CREATE_LABEL('THONGBAO_OLS',1250,'TDV:HTTT,CNPM,KHMT,CNTT,TGMT,MMT:CS1');
-- d) Hãy cho biết nhãn của dòng thông báo t1 để t1 được phát tán (đọc) bởi tất cả Trưởng đơn vị: 
--> t1: TDV/ GV/ GVU/ NV/ SV
-- e) Hãy cho biết nhãn của dòng thông báo t2 để phát tán t2 đến Sinh viên thuộc ngành HTTT học ở Cơ sở 1: 
--> t2: SV/ SV:: CS1/ SV::CS1,CS2/ SV:HTTT:CS1/ SV:HTTT:CS1,CS2
-- f) Hãy cho biết nhãn của dòng thông báo t3 để phát tán t3 đến Trưởng bộ môn KHMT ở Cơ sở 1: 
--> t3: TBM/ TBM::CS1/ TBM::CS1,CS2/ TBM:KHMT:CS1/ TBM:KHMT:CS1,CS2/ GV/ GVU/...
-- g) Cho biết nhãn của dòng thông báo t4 để phát tán t4 đến Trưởng bộ môn KHMT ở Cơ sở 1 và Cơ sở 2: 
--> t4: TBM/ TBM::CS1,CS2/ TBM:KHMT:CS1,CS2/ GV/...
-- h) Hãy cho thêm 3 chính sách phát tán dòng dữ liệu nữa trên mô hình OLS đã cài đặt:
-- h.1) Nhãn của dòng thông báo t5 để phát tán t5 cho Giảng viên thuộc bộ môn CNPM ở Cơ sở 1:
--> t5: GV/ GV::CS1/ GV::CS1,CS2/ GV:CNPM/ GV:CNPM:CS1/ GV:CNPM:CS1,CS2/ GV/ NV/ SV/...
-- h.2) Hãy cho biết nhãn của dòng thông báo t6 để phát tán t6 đến toàn bộ người dùng:
--> t6: SV
-- h.3) Hãy cho biết nhãn của dòng thông báo t7 để phát tán t7 đến Nhân viên ở Cơ sở 2:
--> t7: NV/ NV::CS2/ NV::CS1,CS2/ SV/ SV::CS1/ SV::CS1,CS2
EXECUTE SA_LABEL_ADMIN.CREATE_LABEL('THONGBAO_OLS',2210,'GVU:HTTT,CNPM,KHMT,CNTT,TGMT,MMT:CS1');
EXECUTE SA_LABEL_ADMIN.CREATE_LABEL('THONGBAO_OLS',2000,'GVU:HTTT:CS1');
EXECUTE SA_LABEL_ADMIN.CREATE_LABEL('THONGBAO_OLS',2001,'SV');
EXECUTE SA_LABEL_ADMIN.CREATE_LABEL('THONGBAO_OLS',2002,'SV:HTTT:CS1'); -- Sinh viên thuộc ngành HTTT học ở Cơ sở 1
EXECUTE SA_LABEL_ADMIN.CREATE_LABEL('THONGBAO_OLS',2003,'TDV:KHMT:CS1'); -- Trưởng bộ môn KHMT ở Cơ sở 1.
EXECUTE SA_LABEL_ADMIN.CREATE_LABEL('THONGBAO_OLS',2004,'TDV:KHMT:CS1,CS2'); -- Trưởng bộ môn KHMT ở Cơ sở 1, Cơ sở 2.
EXECUTE SA_LABEL_ADMIN.CREATE_LABEL('THONGBAO_OLS',2005,'SV::CS1,CS2');
EXECUTE SA_LABEL_ADMIN.CREATE_LABEL('THONGBAO_OLS',2006,'SV:CNPM:CS1');
EXECUTE SA_LABEL_ADMIN.CREATE_LABEL('THONGBAO_OLS',2007,'SV:TGMT');
EXECUTE SA_LABEL_ADMIN.CREATE_LABEL('THONGBAO_OLS',2008,'GVU::CS1,CS2');
EXECUTE SA_LABEL_ADMIN.CREATE_LABEL('THONGBAO_OLS',2009,'NV:KHMT:CS1,CS2');
EXECUTE SA_LABEL_ADMIN.CREATE_LABEL('THONGBAO_OLS',2010,'SV:HTTT:CS1,CS2');
EXECUTE SA_LABEL_ADMIN.CREATE_LABEL('THONGBAO_OLS',2011,'TK:HTTT:CS1');
EXECUTE SA_LABEL_ADMIN.CREATE_LABEL('THONGBAO_OLS',2012,'TK:CNPM:CS2');
EXECUTE SA_LABEL_ADMIN.CREATE_LABEL('THONGBAO_OLS',2013,'TK:KHMT:CS1');
EXECUTE SA_LABEL_ADMIN.CREATE_LABEL('THONGBAO_OLS',2014,'TK:CNTT:CS2');
EXECUTE SA_LABEL_ADMIN.CREATE_LABEL('THONGBAO_OLS',2015,'GVU');
EXECUTE SA_LABEL_ADMIN.CREATE_LABEL('THONGBAO_OLS',2016, 'GV:CNPM:CS1'); -- Giảng viên thuộc bộ môn CNPM ở Cơ sở 1
EXECUTE SA_LABEL_ADMIN.CREATE_LABEL('THONGBAO_OLS',2017,'NV::CS2'); -- Nhân viên ở Cơ sở 2
--B8: UPDATE ĐỂ KHỞI TẠO LABEL TRONG BẢNG THONGBAO (OPTION=NO_CONTROL)
UPDATE THONGBAO 
SET ROW_LABEL = CHAR_TO_LABEL('THONGBAO_OLS', 'TK:HTTT:CS1')
WHERE CAPBACTHAMGIA <= 4 AND LINHVUC = 1 AND COSO = 1;
UPDATE THONGBAO 
SET ROW_LABEL = CHAR_TO_LABEL('THONGBAO_OLS', 'TK:CNPM:CS2')
WHERE CAPBACTHAMGIA = 1 AND LINHVUC = 2 AND COSO = 0;
UPDATE THONGBAO 
SET ROW_LABEL = CHAR_TO_LABEL('THONGBAO_OLS', 'TK:KHMT:CS1')
WHERE CAPBACTHAMGIA = 1 AND LINHVUC = 3 AND COSO = 1;
UPDATE THONGBAO 
SET ROW_LABEL = CHAR_TO_LABEL('THONGBAO_OLS', 'TK:CNTT:CS2')
WHERE CAPBACTHAMGIA = 1 AND LINHVUC = 4 AND COSO = 0;
UPDATE THONGBAO 
SET ROW_LABEL = CHAR_TO_LABEL('THONGBAO_OLS', 'TK:HTTT:CS1')
WHERE CAPBACTHAMGIA = 1 AND LINHVUC = 1 AND COSO = 1;
UPDATE THONGBAO 
SET ROW_LABEL = CHAR_TO_LABEL('THONGBAO_OLS', 'SV')
WHERE CAPBACTHAMGIA = 6 AND LINHVUC = 0;
UPDATE THONGBAO 
SET ROW_LABEL = CHAR_TO_LABEL('THONGBAO_OLS', 'SV::CS1,CS2')
WHERE CAPBACTHAMGIA = 4 AND LINHVUC = 0;
UPDATE THONGBAO 
SET ROW_LABEL = CHAR_TO_LABEL('THONGBAO_OLS', 'SV::CS1')
WHERE CAPBACTHAMGIA = 3 AND LINHVUC = 0 AND COSO = 1;
UPDATE THONGBAO 
SET ROW_LABEL = CHAR_TO_LABEL('THONGBAO_OLS', 'SV:TGMT')
WHERE CAPBACTHAMGIA = 6 AND LINHVUC = 5 AND COSO = 1;
UPDATE THONGBAO 
SET ROW_LABEL = CHAR_TO_LABEL('THONGBAO_OLS', 'NV:KHMT:CS1,CS2')
WHERE CAPBACTHAMGIA = 2 AND LINHVUC = 0 AND COSO = 2;
UPDATE THONGBAO 
SET ROW_LABEL = CHAR_TO_LABEL('THONGBAO_OLS', 'NV:KHMT:CS1,CS2')
WHERE CAPBACTHAMGIA = 6 AND LINHVUC = 1 AND COSO = 1;
UPDATE THONGBAO 
SET ROW_LABEL = CHAR_TO_LABEL('THONGBAO_OLS', 'GVU')
WHERE CAPBACTHAMGIA = 4 AND LINHVUC = 0 AND COSO = 0;
UPDATE THONGBAO 
SET ROW_LABEL = CHAR_TO_LABEL('THONGBAO_OLS', 'GVU')
WHERE CAPBACTHAMGIA = 4 AND LINHVUC = 5 AND COSO = 0;
UPDATE THONGBAO 
SET ROW_LABEL = CHAR_TO_LABEL('THONGBAO_OLS', 'GVU')
WHERE CAPBACTHAMGIA = 4 AND LINHVUC = 0 AND COSO = 12;
SELECT * FROM THONGBAO
--B9: ÁP DỤNG OLS VÀO BẢNG
BEGIN
SA_POLICY_ADMIN.REMOVE_TABLE_POLICY('THONGBAO_OLS','U_ADMIN','THONGBAO');
SA_POLICY_ADMIN.APPLY_TABLE_POLICY(
    POLICY_NAME  => 'THONGBAO_OLS',
    SCHEMA_NAME  => 'U_ADMIN',
    TABLE_NAME  => 'THONGBAO',
    TABLE_OPTIONS  => 'READ_CONTROL',
    PREDICATE => NULL);
END;
--B10: TẠO USER ĐỂ TEST (CONNECT VÀO SYS)
--B12: CẤP QUYỀN CONNECT CHO CÁC TÀI KHOẢN TEST (CONNECT VÀO SYS)
-- ===== CHAY DUOI QUYEN U_ADMIN =====
--B13: GÁN LABEL CHO USER
BEGIN
SA_USER_ADMIN.SET_USER_LABELS ('THONGBAO_OLS','TK_1','TK:HTTT,CNPM,KHMT,CNTT,TGMT,MMT:CS1,CS2'); --a. Trưởng khoa có thể đọc được toàn bộ thông báo.
SA_USER_ADMIN.SET_USER_LABELS ('THONGBAO_OLS','TDV_2','TDV:HTTT,CNPM,KHMT,CNTT,TGMT,MMT:CS1,CS2'); --b. Trưởng bộ môn phụ trách Cơ sở 2 có thể đọc được toàn bộ thông báo dành cho trưởng bộ môn không phân biệt vị trí địa lý.
SA_USER_ADMIN.SET_USER_LABELS ('THONGBAO_OLS','GVU_88','GVU:HTTT,CNPM,KHMT,CNTT,TGMT,MMT:CS1,CS2'); --c.  Giáo vụ có thể đọc toàn bộ thông báo dành cho giáo vụ 
SA_USER_ADMIN.SET_USER_LABELS ('THONGBAO_OLS','SV_1','SV:HTTT:CS1'); --e. Sinh viên thuộc ngành HTTT học ở Cơ sở 1.
SA_USER_ADMIN.SET_USER_LABELS ('THONGBAO_OLS','SV_2','SV::CS1,CS2'); 
SA_USER_ADMIN.SET_USER_LABELS ('THONGBAO_OLS','TDV_3','TDV:KHMT:CS1'); --f. Trưởng bộ môn KHMT ở Cơ sở 1.
SA_USER_ADMIN.SET_USER_LABELS ('THONGBAO_OLS','TDV_4','TDV:KHMT:CS1,CS2'); --g. Trưởng bộ môn KHMT ở Cơ sở 1, Cơ sở 2.
SA_USER_ADMIN.SET_USER_LABELS ('THONGBAO_OLS','GV_9','GV:CNPM:CS1'); --h.1. Giảng viên thuộc bộ môn CNPM ở Cơ sở 1
SA_USER_ADMIN.SET_USER_LABELS ('THONGBAO_OLS','NVCB_98','NV::CS2'); --h.3. Nhân viên ở Cơ sở 2
END;
/
SELECT * FROM ALL_SA_LABELS;
--B14:CONNECT VÀO USER TEST ĐỂ TEST THỬ (UER: SV_1)
--CONNECT SV_1/SV_1;
--SELECT * FROM U_ADMIN.THONGBAO;
--SHOW USER;